name: Deploy Nodejs Applicatioin to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 #check by github team

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }} #the ip of server is stored in github repo secrets so no one can directly access and we cannot put that in .env file bcz on github it is accessible to every one.
          username: ubuntu
          key: ${{ secrets.SSH_KEY }} #we create this private ssh key and store that in github repo secrets and ubuntu server.
          #cd to place where we want to clone our project
          #make sure to pick public key and putit in server and private key in github ssecrets.
          script: |
            cd /home/ubuntu/project-git/nodejs-application-deploy-github-actions
            git pull
            docker compose up -d --build

#when you push this file to github, the github actions file will run atomatically.